### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by dezren39** [chrillefkr/nixos-unattended-installer#1]
love this! mind licensing it mit or some such? might end up using something like this to make my initial minimal nixos image, then maybe ssh updates after that

**Comment by Zocker1999NET** [comment]
I’m on a similar page here. I really like the simplicity of this project & am thankful that you decided to publish this to GitHub, but I refrain from using it because I’m legally not allowed to modify. Read https://choosealicense.com/no-permission/ or https://opensource.stackexchange.com/q/1720 for more information.

Because I would like to add a mechanism to automatically retrieve the host name via DHCP or Reverse DNS. Combined with setting a flake, this makes it easily possible to build a single ISO for yourself & re-use it on VMs or even real hosts without the need for further deployment tools or manual installation.

**Comment by chrillefkr** [comment]
There ya go, MIT it is. Bear in mind that I will add some changes to this repo (whenever I get my thumb out of my a**), hopefully features you'll appreciate. Consider the API unstable, and maybe do changes in your own forks for now.
